name: Issue Accepted Workflow
on:
  issues:
    types:
      - labeled

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if issue labels are changed to "accepted"
        id: check_labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueNumber = context.payload.issue.number;
            const labels = issue.labels.map(label => label.name);
            const hasAcceptedLabel = labels.includes("new license/exception: Accepted");
            console.log(`::set-output name=hasAcceptedLabel::${hasAcceptedLabel}`);
            console.log(`::set-output name=issueNumber::${issueNumber}`);
            return { hasAcceptedLabel }

      - name: Generate .txt and .xml files
        id: step1
        if: ${{ steps.check_labels.outputs.hasAcceptedLabel == 'true' }}
        run: |
          # Add your code here to run the task once the issue is labeled as "accepted"
          python issueAccepted.py ${{ steps.check_labels.outputs.hasAcceptedLabel }}
          echo "Task triggered! ${{steps.check_labels.outputs.hasAcceptedValue}}"
          echo "The output value is ${{ steps.check_labels.outputs.hasAcceptedLabel }}"
          echo "::set-output name=myOutput::Hello Vedant!!!!"

      - name: Use output value
        run: echo "The output value is ${{ steps.step1.outputs.myOutput }}"
