name: Issue Accepted Workflow
on:
  issues:
    types:
      - labeled

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue labels are changed to "accepted"
        id: check_labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name);
            const hasAcceptedLabel = labels.includes("Accepted");
            return { labels }

      - name: Generate .txt and .xml files
        id: step1
        run: |
          # Add your code here to run the task once the issue is labeled as "accepted"
          echo "Task triggered! ${{steps.check_labels.outputs.result}}"
          echo "::set-output name=myOutput::Hello, World!"

      - name: Use output value
        run: echo "The output value is ${{ steps.step1.outputs.myOutput }}"
